### ISSUE TITLE
can start proxy

### ISSUE THREAD

**Issue by yswtrue** [flathub/io.github.Fndroid.clash_for_windows#1]
always stay on disconnected.
![image](https://user-images.githubusercontent.com/1270490/148046496-9119270e-a456-47b4-9488-f5ae4edcd702.png)

```
➜  ~ flatpak run io.github.Fndroid.clash_for_windows
[2 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/extra/clash_for_windows/cfw --type=zygote --enable-crashpad
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 18:34:14.981: Failed to load module "xapp-gtk3-module"
Gtk-Message: 18:34:14.981: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:34:14.981: Failed to load module "appmenu-gtk-module"
[43:0104/183415.075414:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Comment by qvshuo** [comment]
> 

Did you import the Profiles using your subscription link? It won't work without it.

**Comment by yswtrue** [comment]
I have profiles, but I can't switch profiles.
![image](https://user-images.githubusercontent.com/1270490/148048268-a54ca23c-7f4a-4266-a6d4-7cd43e4aadc4.png)

**Comment by yswtrue** [comment]
os: manjaro os test branch

**Comment by qvshuo** [comment]
> I have profiles, but I can't switch profiles. ![image](https://user-images.githubusercontent.com/1270490/148048268-a54ca23c-7f4a-4266-a6d4-7cd43e4aadc4.png)

Refer to [this link](https://github.com/Fndroid/clash_for_windows_pkg/issues/349) for the solution. I will open a virtual machine to see if it's a subscription link issue, because it works fine on my machine.

**Comment by qvshuo** [comment]
> os: manjaro os test branch

Refer to [this link](https://github.com/Fndroid/clash_for_windows_pkg/issues/349) for the solution. I will open a virtual machine to see if it's a subscription link issue, because it works fine on my machine.

**Comment by yswtrue** [comment]
It isn't yaml problem, I run cfw of aur version, it works fine for me.

**Comment by qvshuo** [comment]
> It isn't yaml problem, I run cfw of aur version, it works fine for me.

I spent some time installing Manjaro in a virtual machine and installed the flatpak version of cfw and everything worked fine. I suggest you try to quit cfw and then delete all files in `~/.config/clash` and `~/.var/app/io.github.Fndroid.clash_for_windows/config/clash_win` and try to download the subscription again.

**Comment by yswtrue** [comment]
> > It isn't yaml problem, I run cfw of aur version, it works fine for me.
> 
> I spent some time installing Manjaro in a virtual machine and installed the flatpak version of cfw and everything worked fine. I suggest you try to quit cfw and then delete all files in `~/.config/clash` and `~/.var/app/io.github.Fndroid.clash_for_windows/config/clash_win` and try to download the Profiles again.

It works well now, thank you very much.

**Comment by yswtrue** [comment]
But it seams can't start service mode, when I click install there is no password input dialog, and nothing happends.

**Comment by yswtrue** [comment]
And when I restart cfw it stay in disconnected again.

**Comment by qvshuo** [comment]
> But it seams can't start service mode, when I click install there is no password input dialog, and nothing happends.

Because of the limitation of flatpak, service mode does not work now by clicking "Install".

**Comment by qvshuo** [comment]
> And when I restart cfw it stay in disconnected again.

The linux version of cfw will exit with a residual process called `clash-linux`, so perhaps opening your system monitor and kill this process will often solve the problem.

**Comment by lumingzh** [comment]
flatpak 是沙盒环境，修改系统服务这种操作应该是不允许的。
