### ISSUE TITLE
Remove --filesystem=xdg-config/clash:create

### ISSUE THREAD

**Issue by lumingzh** [flathub/io.github.Fndroid.clash_for_windows#2]
flatpak apps should store all data in their own folders under ~/.var/app/appname without touch filesystem, I think this is how flatpak designed. And should remove xdg-config/ro: permission as well.

**Comment by lumingzh** [comment]
correct me if  I am wrong.

**Comment by qvshuo** [comment]
> flatpak apps should store all data in their own folders under ~/.var/app/appname without touch filesystem, I think this is how flatpak designed. And should remove xdg-config/ro: permission as well.

Thank you very much for your suggestion. cfw has this directory hardcoded, and not giving the program access to the ~/.config/clash directory will cause the program to fail.
The application can only create the directory ~/.var/app/appname/.config/clash_win in the sandbox, not the directory ~/.var/app/appname/.config/clash in the sandbox.
Thanks again.
