### ISSUE TITLE
Can't create or read config files and profiles after update to version 0.20.6

### ISSUE THREAD

**Issue by lumingzh** [flathub/io.github.Fndroid.clash_for_windows#39]
I see this build change: 

![截图 2022-10-23 17-55-15](https://user-images.githubusercontent.com/89230850/197385677-21344ab3-7a3b-4df6-a014-7b2453f0b3a7.png)

I can assume that hardcoded path doesn't change upstream, so why change this?

**Comment by qvshuo** [comment]
> I see this build change:
> 
> ![截图 2022-10-23 17-55-15](https://user-images.githubusercontent.com/89230850/197385677-21344ab3-7a3b-4df6-a014-7b2453f0b3a7.png)
> 
> I can assume that hardcoded path doesn't change upstream, so why change this?

Is it not working right now?
The original configuration failed at build time with the error: "finish-args-unnecessary-xdg-config-access", so I changed it.

**Comment by lumingzh** [comment]
> > I see this build change:
> > ![截图 2022-10-23 17-55-15](https://user-images.githubusercontent.com/89230850/197385677-21344ab3-7a3b-4df6-a014-7b2453f0b3a7.png)
> > I can assume that hardcoded path doesn't change upstream, so why change this?
> 
> Is it not working right now? The original configuration failed at build time with the error: "finish-args-unnecessary-xdg-config-access", so I changed it.

No, not working.

**Comment by qvshuo** [comment]
> > > I see this build change:
> > > ![截图 2022-10-23 17-55-15](https://user-images.githubusercontent.com/89230850/197385677-21344ab3-7a3b-4df6-a014-7b2453f0b3a7.png)
> > > I can assume that hardcoded path doesn't change upstream, so why change this?
> > 
> > 
> > Is it not working right now? The original configuration failed at build time with the error: "finish-args-unnecessary-xdg-config-access", so I changed it.
> 
> No, not working.

i have try to fix this issue, maybe you can run this command now:
flatpak install --user https://dl.flathub.org/build-repo/115427/io.github.Fndroid.clash_for_windows.flatpakref

**Comment by lumingzh** [comment]
@qvshuo Ok, everything works normally now, please submit this update thank you.

**Comment by richpurnellai** [comment]
Thanks for the fix, when will flathub sync this update?

**Comment by qvshuo** [comment]
> Thanks for the fix, when will flathub sync this update?

yes I will update it on flathub tonight
