### ISSUE TITLE
Lose config on every start in 0.20.6 (a737ad24)

### ISSUE THREAD

**Issue by sky96111** [flathub/io.github.Fndroid.clash_for_windows#44]
### Prerequisites

* [x] Have you read the readme?
* [x] Have you searched for similar issues?

You can describe your issue in both Chinese and English.

### Description

更新到版本ef5706d51f9b277fbada7bb206d3255d438e91c1b4a5f6b2d5a4a52b0565c910后，每次关闭cfw都会丢失所有的配置文件  
疑似和这条commit有关：https://github.com/flathub/io.github.Fndroid.clash_for_windows/commit/a737ad24a4b234824c9c99cc68a9a9267390bc51

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Environments

```
flatpak info io.github.Fndroid.clash_for_windows

Clash for Windows - Clash's graphical client, based on Electron.

  标识： io.github.Fndroid.clash_for_windows
  引用： app/io.github.Fndroid.clash_for_windows/x86_64/stable
  架构： x86_64
  分支： stable
  版本： 0.20.6
    许可证： LicenseRef-proprietary=https://github.com/Fndroid/clash_for_windows_pkg/issues/153
  来源： flathub
  集合： org.flathub.Stable
  安装： system
    已安装： 3.9 MB
    运行时： org.freedesktop.Platform/x86_64/22.08
 SDK： org.freedesktop.Sdk/x86_64/22.08

  交付： ef5706d51f9b277fbada7bb206d3255d438e91c1b4a5f6b2d5a4a52b0565c910
  上级： 5f028f07ba048a3b68ca072768cbe2d2f27f78d7a36b5b80c9e26900eb8b53e6
  主题： Update io.github.Fndroid.clash_for_windows.yaml (a737ad24)
  日期： 2022-10-24 15:22:42 +0000

```
OS: openSUSE Tumbleweed
DE: Gnome
APP: 0.20.6 (a737ad24)

**Comment by sky96111** [comment]
尴尬了，丢了一晚上配置，刚发完issue就好了（？

**Comment by qvshuo** [comment]
> 尴尬了，丢了一晚上配置，刚发完issue就好了（？

哈哈，我修了
